services:
  postgres:
    image: postgres:18.0-alpine
    restart: always
    user: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - anonymous_book_review_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-egyahmed.ezzat120@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - anonymous_book_review_network

networks:
  anonymous_book_review_network:
    name: anonymous_book_review_network
    driver: bridge

volumes:
  postgres_data:
  pgadmin:
